// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXEXWI9-lUtPqdckA0NwUd0Fg2Me36-GA',
    appId: '1:46312439935:web:629c9d7cb4c88c33a37f4a',
    messagingSenderId: '46312439935',
    projectId: 'gymtracker-3c18e',
    authDomain: 'gymtracker-3c18e.firebaseapp.com',
    storageBucket: 'gymtracker-3c18e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPwuPiPar-3zD3VjbuYuZgEug351NJH30',
    appId: '1:46312439935:android:73b8991f85201c17a37f4a',
    messagingSenderId: '46312439935',
    projectId: 'gymtracker-3c18e',
    storageBucket: 'gymtracker-3c18e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLeRYkEIJYceOMtiIJMWVYPbxfvqGG4iM',
    appId: '1:46312439935:ios:4ad82f68b8fa42e4a37f4a',
    messagingSenderId: '46312439935',
    projectId: 'gymtracker-3c18e',
    storageBucket: 'gymtracker-3c18e.firebasestorage.app',
    iosBundleId: 'com.example.gymTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLeRYkEIJYceOMtiIJMWVYPbxfvqGG4iM',
    appId: '1:46312439935:ios:4ad82f68b8fa42e4a37f4a',
    messagingSenderId: '46312439935',
    projectId: 'gymtracker-3c18e',
    storageBucket: 'gymtracker-3c18e.firebasestorage.app',
    iosBundleId: 'com.example.gymTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXEXWI9-lUtPqdckA0NwUd0Fg2Me36-GA',
    appId: '1:46312439935:web:7f016bf7fcec847fa37f4a',
    messagingSenderId: '46312439935',
    projectId: 'gymtracker-3c18e',
    authDomain: 'gymtracker-3c18e.firebaseapp.com',
    storageBucket: 'gymtracker-3c18e.firebasestorage.app',
  );
}
